name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

defaults:
  run:
    working-directory: AzureContainersWebsite
# SECOND STEP
env:
  imagetag: ${{ date +%s }}
  
jobs:
  
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag azurecontainerswebsite:$imagetag

# SECOND STEP: PUBLISH AS ARTIFACT
    - name: Save Image as Tar
      run: docker save -o azurecontainerswebsite.tar azurecontainerswebsite:$imagetag

    - name: Upload Image as Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:      
        name: ACWImage
        path: azurecontainerswebsite.tar
